# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_windowoPmhJD.ui'
##
## Created by: Qt User Interface Compiler version 6.11.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGraphicsView, QGridLayout,
    QLabel, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QStackedWidget, QTextBrowser,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QSize(800, 600))
        MainWindow.setMaximumSize(QSize(800, 600))
        self.actioncheck_gained_character = QAction(MainWindow)
        self.actioncheck_gained_character.setObjectName(u"actioncheck_gained_character")
        self.actionquick_check_character_potential_phase = QAction(MainWindow)
        self.actionquick_check_character_potential_phase.setObjectName(u"actionquick_check_character_potential_phase")
        self.actioncheck_gained_arsenal = QAction(MainWindow)
        self.actioncheck_gained_arsenal.setObjectName(u"actioncheck_gained_arsenal")
        self.actionquick_check_arsenal_potential_phase = QAction(MainWindow)
        self.actionquick_check_arsenal_potential_phase.setObjectName(u"actionquick_check_arsenal_potential_phase")
        self.actiontoken_aic_quota_exchange = QAction(MainWindow)
        self.actiontoken_aic_quota_exchange.setObjectName(u"actiontoken_aic_quota_exchange")
        self.actioncheck_special_stock = QAction(MainWindow)
        self.actioncheck_special_stock.setObjectName(u"actioncheck_special_stock")
        self.actionvolume = QAction(MainWindow)
        self.actionvolume.setObjectName(u"actionvolume")
        self.actionanimate = QAction(MainWindow)
        self.actionanimate.setObjectName(u"actionanimate")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.animate_widget = QWidget(self.centralwidget)
        self.animate_widget.setObjectName(u"animate_widget")
        self.animate_widget.setGeometry(QRect(0, 0, 800, 600))
        self.animate_widget.setMinimumSize(QSize(800, 600))
        self.animate_widget.setMaximumSize(QSize(800, 600))
        self.stackedWidget = QStackedWidget(self.animate_widget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 800, 600))
        self.stackedWidget.setMinimumSize(QSize(800, 600))
        self.stackedWidget.setMaximumSize(QSize(800, 600))
        self.main_widget = QWidget(self.centralwidget)
        self.main_widget.setObjectName(u"main_widget")
        self.main_widget.setGeometry(QRect(0, 0, 800, 600))
        self.main_widget.setMinimumSize(QSize(800, 600))
        self.main_widget.setMaximumSize(QSize(800, 600))
        self.label_3 = QLabel(self.main_widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(735, 140, 41, 16))
        self.create_log = QPushButton(self.main_widget)
        self.create_log.setObjectName(u"create_log")
        self.create_log.setGeometry(QRect(582, 520, 91, 26))
        self.origeometry_label = QLabel(self.main_widget)
        self.origeometry_label.setObjectName(u"origeometry_label")
        self.origeometry_label.setGeometry(QRect(30, 33, 61, 16))
        self.chartered_permit_label = QLabel(self.main_widget)
        self.chartered_permit_label.setObjectName(u"chartered_permit_label")
        self.chartered_permit_label.setGeometry(QRect(30, 63, 71, 16))
        self.character_pull_one = QPushButton(self.main_widget)
        self.character_pull_one.setObjectName(u"character_pull_one")
        self.character_pull_one.setGeometry(QRect(220, 430, 151, 51))
        self.label_2 = QLabel(self.main_widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(530, 60, 60, 30))
        self.present_character_pool = QTextBrowser(self.main_widget)
        self.present_character_pool.setObjectName(u"present_character_pool")
        self.present_character_pool.setGeometry(QRect(600, 20, 120, 30))
        self.arsenal_ticket_label = QLabel(self.main_widget)
        self.arsenal_ticket_label.setObjectName(u"arsenal_ticket_label")
        self.arsenal_ticket_label.setGeometry(QRect(350, 63, 54, 16))
        self.arsenal_ticket = QTextBrowser(self.main_widget)
        self.arsenal_ticket.setObjectName(u"arsenal_ticket")
        self.arsenal_ticket.setGeometry(QRect(430, 60, 71, 21))
        self.chartered_permit = QTextBrowser(self.main_widget)
        self.chartered_permit.setObjectName(u"chartered_permit")
        self.chartered_permit.setGeometry(QRect(110, 60, 71, 21))
        self.enter_acquisition_center = QPushButton(self.main_widget)
        self.enter_acquisition_center.setObjectName(u"enter_acquisition_center")
        self.enter_acquisition_center.setGeometry(QRect(582, 440, 191, 26))
        self.check_character_log = QPushButton(self.main_widget)
        self.check_character_log.setObjectName(u"check_character_log")
        self.check_character_log.setGeometry(QRect(582, 480, 91, 26))
        self.arsenal_pull_ten = QPushButton(self.main_widget)
        self.arsenal_pull_ten.setObjectName(u"arsenal_pull_ten")
        self.arsenal_pull_ten.setGeometry(QRect(220, 500, 331, 51))
        self.six_star_guarantee_count = QTextBrowser(self.main_widget)
        self.six_star_guarantee_count.setObjectName(u"six_star_guarantee_count")
        self.six_star_guarantee_count.setGeometry(QRect(720, 210, 71, 21))
        self.basic_permit = QTextBrowser(self.main_widget)
        self.basic_permit.setObjectName(u"basic_permit")
        self.basic_permit.setGeometry(QRect(430, 30, 71, 21))
        self.check_arsenal_log = QPushButton(self.main_widget)
        self.check_arsenal_log.setObjectName(u"check_arsenal_log")
        self.check_arsenal_log.setGeometry(QRect(680, 480, 91, 26))
        self.set_arsenal_pool = QPushButton(self.main_widget)
        self.set_arsenal_pool.setObjectName(u"set_arsenal_pool")
        self.set_arsenal_pool.setGeometry(QRect(720, 60, 80, 30))
        self.origeometry = QTextBrowser(self.main_widget)
        self.origeometry.setObjectName(u"origeometry")
        self.origeometry.setGeometry(QRect(110, 30, 71, 21))
        self.oroberyl_label = QLabel(self.main_widget)
        self.oroberyl_label.setObjectName(u"oroberyl_label")
        self.oroberyl_label.setGeometry(QRect(190, 33, 41, 16))
        self.character_pull_ten = QPushButton(self.main_widget)
        self.character_pull_ten.setObjectName(u"character_pull_ten")
        self.character_pull_ten.setGeometry(QRect(400, 430, 151, 51))
        self.spectral_permit_label = QLabel(self.main_widget)
        self.spectral_permit_label.setObjectName(u"spectral_permit_label")
        self.spectral_permit_label.setGeometry(QRect(190, 63, 71, 16))
        self.present_arsenal_pool = QTextBrowser(self.main_widget)
        self.present_arsenal_pool.setObjectName(u"present_arsenal_pool")
        self.present_arsenal_pool.setGeometry(QRect(600, 60, 120, 30))
        self.spectral_permit = QTextBrowser(self.main_widget)
        self.spectral_permit.setObjectName(u"spectral_permit")
        self.spectral_permit.setGeometry(QRect(270, 60, 71, 21))
        self.gridLayoutWidget = QWidget(self.main_widget)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(100, 100, 611, 321))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.graphicsView_4 = QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_4.setObjectName(u"graphicsView_4")

        self.gridLayout.addWidget(self.graphicsView_4, 0, 3, 1, 1)

        self.graphicsView_6 = QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_6.setObjectName(u"graphicsView_6")

        self.gridLayout.addWidget(self.graphicsView_6, 1, 0, 1, 1)

        self.graphicsView_5 = QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_5.setObjectName(u"graphicsView_5")

        self.gridLayout.addWidget(self.graphicsView_5, 0, 4, 1, 1)

        self.graphicsView_8 = QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_8.setObjectName(u"graphicsView_8")

        self.gridLayout.addWidget(self.graphicsView_8, 1, 2, 1, 1)

        self.graphicsView_3 = QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_3.setObjectName(u"graphicsView_3")

        self.gridLayout.addWidget(self.graphicsView_3, 0, 2, 1, 1)

        self.graphicsView_2 = QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_2.setObjectName(u"graphicsView_2")

        self.gridLayout.addWidget(self.graphicsView_2, 0, 1, 1, 1)

        self.graphicsView_9 = QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_9.setObjectName(u"graphicsView_9")

        self.gridLayout.addWidget(self.graphicsView_9, 1, 3, 1, 1)

        self.graphicsView_7 = QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_7.setObjectName(u"graphicsView_7")

        self.gridLayout.addWidget(self.graphicsView_7, 1, 1, 1, 1)

        self.graphicsView_1 = QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_1.setObjectName(u"graphicsView_1")

        self.gridLayout.addWidget(self.graphicsView_1, 0, 0, 1, 1)

        self.graphicsView_10 = QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_10.setObjectName(u"graphicsView_10")

        self.gridLayout.addWidget(self.graphicsView_10, 1, 4, 1, 1)

        self.set_character_pool = QPushButton(self.main_widget)
        self.set_character_pool.setObjectName(u"set_character_pool")
        self.set_character_pool.setGeometry(QRect(720, 20, 80, 30))
        self.basic_permit_label = QLabel(self.main_widget)
        self.basic_permit_label.setObjectName(u"basic_permit_label")
        self.basic_permit_label.setGeometry(QRect(350, 33, 81, 16))
        self.total_count = QTextBrowser(self.main_widget)
        self.total_count.setObjectName(u"total_count")
        self.total_count.setGeometry(QRect(720, 160, 71, 20))
        self.checkBox = QCheckBox(self.main_widget)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(720, 250, 81, 20))
        self.oroberyl = QTextBrowser(self.main_widget)
        self.oroberyl.setObjectName(u"oroberyl")
        self.oroberyl.setGeometry(QRect(270, 30, 71, 21))
        self.label_4 = QLabel(self.main_widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(735, 190, 54, 16))
        self.save_log = QPushButton(self.main_widget)
        self.save_log.setObjectName(u"save_log")
        self.save_log.setGeometry(QRect(680, 520, 91, 26))
        self.label = QLabel(self.main_widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(530, 20, 60, 30))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 800, 33))
        self.menu = QMenu(self.menuBar)
        self.menu.setObjectName(u"menu")
        self.menu_2 = QMenu(self.menu)
        self.menu_2.setObjectName(u"menu_2")
        self.menu_3 = QMenu(self.menu)
        self.menu_3.setObjectName(u"menu_3")
        MainWindow.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menu.menuAction())
        self.menu.addAction(self.menu_2.menuAction())
        self.menu.addAction(self.menu_3.menuAction())
        self.menu.addAction(self.actioncheck_special_stock)
        self.menu.addAction(self.actiontoken_aic_quota_exchange)
        self.menu_2.addAction(self.actioncheck_gained_character)
        self.menu_2.addAction(self.actionquick_check_character_potential_phase)
        self.menu_3.addAction(self.actioncheck_gained_arsenal)
        self.menu_3.addAction(self.actionquick_check_arsenal_potential_phase)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actioncheck_gained_character.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u770b\u62e5\u6709\u7684\u89d2\u8272", None))
        self.actionquick_check_character_potential_phase.setText(QCoreApplication.translate("MainWindow", u"\u4e00\u952e\u63d0\u5347\u6f5c\u80fd", None))
        self.actioncheck_gained_arsenal.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u770b\u62e5\u6709\u7684\u6b66\u5668", None))
        self.actionquick_check_arsenal_potential_phase.setText(QCoreApplication.translate("MainWindow", u"\u4e00\u952e\u63d0\u5347\u6f5c\u80fd", None))
        self.actiontoken_aic_quota_exchange.setText(QCoreApplication.translate("MainWindow", u"\u4fe1\u7269\u5151\u6362\u96c6\u6210\u914d\u989d", None))
        self.actioncheck_special_stock.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u770b\u5176\u4ed6\u7269\u8d44", None))
        self.actionvolume.setText(QCoreApplication.translate("MainWindow", u"volume", None))
        self.actionanimate.setText(QCoreApplication.translate("MainWindow", u"animate", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u603b\u62bd\u6570", None))
        self.create_log.setText(QCoreApplication.translate("MainWindow", u"\u521b\u5efa\u5386\u53f2\u8bb0\u5f55", None))
        self.origeometry_label.setText(QCoreApplication.translate("MainWindow", u"\u884d\u8d28\u6e90\u77f3", None))
        self.chartered_permit_label.setText(QCoreApplication.translate("MainWindow", u"\u7279\u8bb8\u5bfb\u8bbf\u51ed\u8bc1", None))
        self.character_pull_one.setText(QCoreApplication.translate("MainWindow", u"\u89d2\u8272\u5355\u62bd", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u5f53\u524d\u6b66\u5668\u6c60", None))
        self.arsenal_ticket_label.setText(QCoreApplication.translate("MainWindow", u"\u6b66\u5e93\u914d\u989d", None))
        self.enter_acquisition_center.setText(QCoreApplication.translate("MainWindow", u"\u91c7\u8d2d\u4e2d\u5fc3", None))
        self.check_character_log.setText(QCoreApplication.translate("MainWindow", u"\u89d2\u8272\u5386\u53f2\u8bb0\u5f55", None))
        self.arsenal_pull_ten.setText(QCoreApplication.translate("MainWindow", u"\u6b66\u5668\u5341\u8fde", None))
        self.check_arsenal_log.setText(QCoreApplication.translate("MainWindow", u"\u6b66\u5668\u5386\u53f2\u8bb0\u5f55", None))
        self.set_arsenal_pool.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e\u6b66\u5668\u6c60", None))
        self.oroberyl_label.setText(QCoreApplication.translate("MainWindow", u"\u5408\u6210\u7389", None))
        self.character_pull_ten.setText(QCoreApplication.translate("MainWindow", u"\u89d2\u8272\u5341\u8fde", None))
        self.spectral_permit_label.setText(QCoreApplication.translate("MainWindow", u"\u5361\u6c60\u5bfb\u8bbf\u51ed\u8bc1", None))
        self.set_character_pool.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e\u89d2\u8272\u6c60", None))
        self.basic_permit_label.setText(QCoreApplication.translate("MainWindow", u"\u57fa\u7840\u5bfb\u8bbf\u51ed\u8bc1", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"\u8df3\u8fc7\u52a8\u753b", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u5c0f\u4fdd\u5e95", None))
        self.save_log.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u5386\u53f2\u8bb0\u5f55", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u5f53\u524d\u89d2\u8272\u6c60", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u4ed3\u5e93", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"\u89d2\u8272", None))
        self.menu_3.setTitle(QCoreApplication.translate("MainWindow", u"\u6b66\u5668", None))
    # retranslateUi

